anychart.onDocumentReady(function() {
    // create map
    map = anychart.map();

    // create data set
    var dataSet = anychart.data.set([
		{'id': 'AF', 'value': 0},
		{'id': 'AO', 'value': 1},
		{'id': 'AL', 'value': 2},
		{'id': 'AE', 'value': 3},
		{'id': 'AR', 'value': 4},
		{'id': 'AM', 'value': 5},
		{'id': 'TF', 'value': 6},
		{'id': 'AU', 'value': 7},
		{'id': 'AT', 'value': 8},
		{'id': 'AZ', 'value': 9},
		{'id': 'BI', 'value': 10},
		{'id': 'BE', 'value': 11},
		{'id': 'BJ', 'value': 12},
		{'id': 'BF', 'value': 13},
		{'id': 'BD', 'value': 14},
		{'id': 'BG', 'value': 15},
		{'id': 'BA', 'value': 16},
		{'id': 'BY', 'value': 17},
		{'id': 'BZ', 'value': 18},
		{'id': 'BO', 'value': 19},
		{'id': 'BR', 'value': 20},
		{'id': 'BN', 'value': 21},
		{'id': 'BT', 'value': 22},
		{'id': 'BW', 'value': 23},
		{'id': 'CF', 'value': 24},
		{'id': 'CA', 'value': 25},
		{'id': 'CH', 'value': 26},
		{'id': 'CL', 'value': 27},
		{'id': 'CN', 'value': 28},
		{'id': 'CI', 'value': 29},
		{'id': 'CM', 'value': 30},
		{'id': 'Cyprus_U.N._Buffer_Zone', 'value': 31},
		{'id': 'CD', 'value': 32},
		{'id': 'CG', 'value': 33},
		{'id': 'CO', 'value': 34},
		{'id': 'CR', 'value': 35},
		{'id': 'CU', 'value': 36},
		{'id': 'N._Cyprus', 'value': 37},
		{'id': 'CY', 'value': 38},
		{'id': 'CZ', 'value': 39},
		{'id': 'DE', 'value': 40},
		{'id': 'DJ', 'value': 41},
		{'id': 'DK', 'value': 42},
		{'id': 'DO', 'value': 43},
		{'id': 'DZ', 'value': 44},
		{'id': 'EC', 'value': 45},
		{'id': 'EG', 'value': 46},
		{'id': 'ER', 'value': 47},
		{'id': 'ES', 'value': 48},
		{'id': 'EE', 'value': 49},
		{'id': 'ET', 'value': 50},
		{'id': 'FI', 'value': 51},
		{'id': 'FJ', 'value': 52},
		{'id': 'FK', 'value': 53},
		{'id': 'FR', 'value': 54},
		{'id': 'GA', 'value': 55},
		{'id': 'GB', 'value': 56},
		{'id': 'GE', 'value': 57},
		{'id': 'GH', 'value': 58},
		{'id': 'GN', 'value': 59},
		{'id': 'GW', 'value': 60},
		{'id': 'GQ', 'value': 61},
		{'id': 'GR', 'value': 62},
		{'id': 'GL', 'value': 63},
		{'id': 'GT', 'value': 64},
		{'id': 'GY', 'value': 65},
		{'id': 'HN', 'value': 66},
		{'id': 'HR', 'value': 67},
		{'id': 'HT', 'value': 68},
		{'id': 'HU', 'value': 69},
		{'id': 'ID', 'value': 70},
		{'id': 'IN', 'value': 71},
		{'id': 'IE', 'value': 72},
		{'id': 'IR', 'value': 73},
		{'id': 'IQ', 'value': 74},
		{'id': 'IS', 'value': 75},
		{'id': 'IL', 'value': 76},
		{'id': 'IT', 'value': 77},
		{'id': 'JO', 'value': 78},
		{'id': 'JP', 'value': 79},
		{'id': 'KZ', 'value': 80},
		{'id': 'KE', 'value': 81},
		{'id': 'KG', 'value': 82},
		{'id': 'KH', 'value': 83},
		{'id': 'KR', 'value': 84},
		{'id': 'Kosovo', 'value': 85},
		{'id': 'KW', 'value': 86},
		{'id': 'LA', 'value': 87},
		{'id': 'LB', 'value': 88},
		{'id': 'LR', 'value': 89},
		{'id': 'LY', 'value': 90},
		{'id': 'LK', 'value': 91},
		{'id': 'LS', 'value': 92},
		{'id': 'LT', 'value': 93},
		{'id': 'LV', 'value': 94},
		{'id': 'MA', 'value': 95},
		{'id': 'MD', 'value': 96},
		{'id': 'MG', 'value': 97},
		{'id': 'MX', 'value': 98},
		{'id': 'MK', 'value': 99},
		{'id': 'ML', 'value': 100},
		{'id': 'MM', 'value': 101},
		{'id': 'ME', 'value': 102},
		{'id': 'MN', 'value': 103},
		{'id': 'MZ', 'value': 104},
		{'id': 'MR', 'value': 105},
		{'id': 'MW', 'value': 106},
		{'id': 'MY', 'value': 107},
		{'id': 'NA', 'value': 108},
		{'id': 'NC', 'value': 109},
		{'id': 'NE', 'value': 110},
		{'id': 'NG', 'value': 111},
		{'id': 'NI', 'value': 112},
		{'id': 'NL', 'value': 113},
		{'id': 'NO', 'value': 114},
		{'id': 'NP', 'value': 115},
		{'id': 'NZ', 'value': 116},
		{'id': 'OM', 'value': 117},
		{'id': 'PK', 'value': 118},
		{'id': 'PA', 'value': 119},
		{'id': 'PE', 'value': 120},
		{'id': 'PH', 'value': 121},
		{'id': 'PG', 'value': 122},
		{'id': 'PL', 'value': 123},
		{'id': 'PR', 'value': 124},
		{'id': 'KP', 'value': 125},
		{'id': 'PT', 'value': 126},
		{'id': 'PY', 'value': 127},
		{'id': 'PS', 'value': 128},
		{'id': 'QA', 'value': 129},
		{'id': 'RO', 'value': 130},
		{'id': 'RW', 'value': 131},
		{'id': 'EH', 'value': 132},
		{'id': 'SA', 'value': 133},
		{'id': 'SD', 'value': 134},
		{'id': 'SS', 'value': 135},
		{'id': 'SN', 'value': 136},
		{'id': 'SL', 'value': 137},
		{'id': 'SV', 'value': 138},
		{'id': 'Somaliland', 'value': 139},
		{'id': 'SO', 'value': 140},
		{'id': 'RS', 'value': 141},
		{'id': 'SR', 'value': 142},
		{'id': 'SK', 'value': 143},
		{'id': 'SI', 'value': 144},
		{'id': 'SE', 'value': 145},
		{'id': 'SZ', 'value': 146},
		{'id': 'SY', 'value': 147},
		{'id': 'TD', 'value': 148},
		{'id': 'TG', 'value': 149},
		{'id': 'TH', 'value': 150},
		{'id': 'TJ', 'value': 151},
		{'id': 'TM', 'value': 152},
		{'id': 'TL', 'value': 153},
		{'id': 'TN', 'value': 154},
		{'id': 'TR', 'value': 155},
		{'id': 'TW', 'value': 156},
		{'id': 'TZ', 'value': 157},
		{'id': 'UG', 'value': 158},
		{'id': 'UA', 'value': 159},
		{'id': 'UY', 'value': 160},
		{'id': 'US', 'value': 161},
		{'id': 'UZ', 'value': 162},
		{'id': 'VE', 'value': 163},
		{'id': 'VN', 'value': 164},
		{'id': 'YE', 'value': 165},
		{'id': 'ZA', 'value': 166},
		{'id': 'ZM', 'value': 167},
		{'id': 'ZW', 'value': 168},
		{'id': 'RU', 'value': 169}
    ]);

    // create choropleth series
    series = map.choropleth(dataSet);

    // set geoIdField to 'id', this field contains in geo data meta properties
    series.geoIdField('id');

    // set map color settings
    series.colorScale(anychart.scales.linearColor('#deebf7', '#3182bd'));
    series.hovered().fill('#addd8e');

    // set geo data, you can find this map in our geo maps collection
    // https://cdn.anychart.com/#maps-collection
    map.geoData(anychart.maps['world']);

    //set map container id (div)
    map.container('container');

    //initiate map drawing
    map.draw();
});